// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CallCard: typeof import('./src/components/callCard.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ExamplePage: typeof import('./src/components/pages/examplePage.vue')['default']
    ExamplePage2: typeof import('./src/components/pages/examplePage2.vue')['default']
  }
}
